# Generated by Django 4.2 on 2023-04-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_errand_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errand',
            options={'ordering': ['created_time']},
        ),
    ]
